### PR TITLE
Bugfix: env-config.sh line endings

### PR DESCRIPTION
**Pull request by Chryogenic**
Line endings were incorrect for env-config.sh. They were CRLF instead of LF.

Updating the file fixes this error:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/env-config.sh
/docker-entrypoint.sh: line 31: /docker-entrypoint.d/env-config.sh: not found
```

### CODE REVIEW

**Comment by sebassem** [comment]
@Chryogenic Hi Ben, is the script updated in this PR (I only see a comment)?  I still get the same error when deploying

**Comment by Chryogenic** [comment]
The line endings were changed - notice lines 1 to 5 are all green:
image

Were you building the dockerfile locally? Do you mind sharing the error logs?

**Comment by sebassem** [comment]
Sure HYG, the images are built using a GitHub action and pushed to ACR
image

**Comment by Chryogenic** [comment]
I've just tested pulling the repo again and the line endings were back to CRLF. Looks like we might need to do something like this:
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by sebassem** [comment]
> I've just tested pulling the repo again and the line endings were back to CRLF. Looks like we might need to do something like this: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

ok let me try to add this to the repo and deploy again

**Pull request merged**
